### ISSUE TITLE
External Trigger of Core Trigger Module

### ISSUE THREAD

**Issue by gokhankaplayan** [joxie/riscv-debug-security#12]
As specified in the existing debug security specification when mdbgsec.extrigen=1, external trigger are enabled. What is the expected behaviour when the current privilege level is not enabled for debug/trace?

From my perspective there are two alternatives:

Dropping the trigger event
Pending and fire the trigger once it is legal to so according to the existing rule:
Triggers with action = 1 (enter debug mode) will be pending until debug is enabled for corresponding privilege level.
The trigger to start/stop/notify trace module will be pending until the privilege level of the hart is enable for trace in mdbgctl.trcprv/mdbgctl.trcv.
I think the second option is better and we should specify this behaviour in the spec.

**Comment by AoteJin** [comment]
I think it could splitted into 2 aspects: 

1. The debugger's privilege does not suffice. In this case, we could just drop it silently. Because the scenario could be that we have several partitions and we only allow debug in partition 1 and the trigger hit in partition 2. We definitely do not want the matched trigger in partition 1 fires when we are debugging partition 0 (kind of side channel).
2. The trigger is asynchronous and fires off when privilege already escalated. For this circumstance, we could discuss specifically in #16

**Comment by AoteJin** [comment]
Per previous discussion @gokhankaplayan mentioned that the external trigger is not associated with any privilege thus we could not associate it with privileges and drop it according to privilege control.
However, the debug spec also has the statement:

_"The TM external trigger input can signal when the trigger is prevented from firing due to one of the mechanisms in section 5.4. An implementation may either ignore the signal altogether when it cannot fire (dropping the trigger event) or it may hold the action as pending and fire the trigger once it is legal to do so."_

Thus, I think just dropping it when the hart is not debuggable is still a simple and legal choice.

**Comment by gokhankaplayan** [comment]
I believe we should follow the same rule as Debug Spec. Both options (dropping and pending) should be legal. I do not see a security problem for both of them. If an implementation drops them, the trigger action is unreliable depending on its use case. For example if the use case is putting hardware breakpoint in M-mode exception handler (Section 5.4 in Debug Spec), dropping might be acceptable. I do not think it is acceptable for external triggers.

**Comment by AoteJin** [comment]
The external trigger could be bi-directional that the input signal to Trigger Module could be, for instance, interrupt, performance counter overflow etc., while the output could be signaled just like the normal triggers by configuring action field.
Actually by current definition in external debug proposal, the external trigger output is in some sense dropped if the action is configured to 8/9 when the privilege doesn't suffice. The only exception is when the trigger type is 7(tmexttrigger).
As with the external trigger input, I checked out CLIC spec, while I am not sure about the real use case, but intuitively it seems a info leak if we pending the interrupt (might be only routed to machine mode) or perf counter overflow (of machine mode) signaling pending and handle it in less privileged debugger.

**Comment by gokhankaplayan** [comment]
As you said dropping the action is fine if the action is configured to 8/9 when the privilege doesn't suffice. The problem is about the trigger type is 7(tmexttrigger). The use case in my mind is that cores interacts with each other by using external tigger to halt or trace-related actions. I do not think pending option creates an security problem for this use case. Other use cases (Interrupt or HPM Counter overflow) can cause security leaks. Dropping them if the privilege suffice with debug enable does not solve the problem. For these use cases, tmextrigger.select should be forced to inactive if m-mode debug is disabled.

**Comment by AoteJin** [comment]
I agree, in the case of halting other harts, pending the trigger signal looks reasonable. Let me sum it up, when the privilege does not suffice:
1. triggers with action of 8/9 should be dropped
2. triggers configured to type 7(tmexttrigger)
2.1 the external trigger sources associated privilege should be constrained when configuing  tmexttrigger.select 
2.2 other general external triggers could either be dropped or pended.

**Comment by gokhankaplayan** [comment]
Thank you @AoteJin , I am on the same page with you about your summary.
