### ISSUE TITLE
Debug module and core interaction

### ISSUE THREAD

**Issue by IMG-S-Hopton** [joxie/riscv-debug-security#17]
There are numerous mentions in the "core changes" section of the spec which mention debug module CSR fields - the secure debug spec should probably be split into Sdext/Sdtrig/DM?

Could we get some clarifications on the following please? 

> hartreset/resethaltreq will get security fault error from selected hart if M mode debug is disabled.
> Halt request behaviors changes as the following
>- If debug is disabled in all modes, halt request will return security fault error （cmderr set to 6)
>- if debug is enabled in any modes, halt request will be pending **un**til the hart can be halted

Using hartreset as an example, is the expectation:
1. hartreset is sent to the core and the core is expected to mask this reset case?
2. when hartreset is attempted to be set, the debug module is aware of mdbgsec values and raises the error at that point?

1 has some implications on how resets are fed to cores and requires the hart to respond to a reset with a denial but ensures the most recent mdbgsec value.

2 seems more reasonable to implement in a system; there's a potential race condition if mdbgsec is changing at the same time as the hartreset bit is attempted to be set but as I mention below there may be other reset mechanisms in the system and changing mdbgsec while debugging with M mode permissions already granted seems like it would have race conditions anyway?

Same with halt request when there's no vs some permissions - can this be handled by the debug module? 

For resethaltreq, does it matter whether M mode debug is enabled or not at the time the bit is set? Doesn't the reset value of mdbgsec matter more? 

My thinking is that if we default to all permissions and then take them away using M-mode software there may be other reset mechanisms available which could then move the hart into a state where M-mode is allowed at which point you can then request halt to debug mode, so if you want to use mdbgsec the safest thing to do is to reset to no permissions as anything else potentially allows an attack anyway?

n.b. the debug spec itself never mentions cmderr in Sdext; so keeping cmderr 6 conditions inside the DM also helps keep the spec and ISA/non-ISA sections cleaner

**Comment by joxie** [comment]
>> There are numerous mentions in the "core changes" section of the spec which mention debug module CSR fields - the secure debug spec should probably be split into Sdext/Sdtrig/DM?

Agreed that we need to split the extension into ISA (Hart) and non ISA extensions (DM) and give them different names

**Comment by gokhankaplayan** [comment]
> hartreset/resethaltreq will get security fault error from selected hart if M mode debug is disabled.

I am in favour of moving resethaltreq/hartreset from Core changes to DM changes for the ease of implementation and proper ISA/non-ISA separation. If you control them with current mdbgsec CSR value, race conditions are unavoidable due to the latency between harts and DM in the implementation. I propose to control them with the default value of mdbgsec to avoid race conditions. I think it is totally fine for resethaltreq, but not sure about hartreset from debug user perspective. 

> If debug is disabled in all modes, halt request will return security fault error（cmderr set to 6)

I propose to remove this statement or add it as optional. As far as I aware most of the implementations does not support denial for hart requests since they implement halt request as a debug interrupt. Moreover, if it remains as pending, it can be debugged after software change mdbgsec value later on.

**Comment by AoteJin** [comment]
>1. hartreset is sent to the core and the core is expected to mask this reset case?
> 2. when hartreset is attempted to be set, the debug module is aware of mdbgsec values and raises the error at that point?

I don't see any difference between those two implementation. Because there will be race conditions in both of them. Mdbgsec is designed to be changeable, either by core or reset. Wherever the rule checking happens, there will be the case that debugger send the request and mdbgsec is changing. Moreover, I think false-alarm is fine and in race condition we could always choose the conservative way to check the accessibility. 

> My thinking is that if we default to all permissions and then take them away using M-mode software there may be other reset mechanisms available which could then move the hart into a state where M-mode is allowed at which point you can then request halt to debug mode, so if you want to use mdbgsec the safest thing to do is to reset to no permissions as anything else potentially allows an attack anyway?

Yes, it is true. We think the default value is implementation specific and different vendors have different use cases, thus we didn't enforce the default value. For example, people might want to debug the ROM of M-mode before the chip is delivered, and afterwards ROM is not debuggable. In this case, they could achieve it by fusing to flip the default value.

**Comment by joxie** [comment]
> I propose to remove this statement or add it as optional. As far as I aware most of the implementations does not support denial for hart requests since they implement halt request as a debug interrupt. Moreover, if it remains as pending, it can be debugged after software change mdbgsec value later on.

@gokhankaplayan just to make sure I understand, do you mean, halt request can be ignored or can be pending forever if not served?

I was wondering if hart can output one bit signal to DM to indicate external debug is disabled then DM can update status in local..

**Comment by AoteJin** [comment]
Actually we do defined the bits to indicate whether the hart is in a debuggable state (in dev branch). 

Field | Bit | Description | Access | Reset
-- | -- | -- | -- | --
allsecured | 21 | The field is 1 when all currently selected hart are secured and not running in debuggable privilege levels | R/W | 0
anysecured | 20 | The field is 1 when any currently selected hart is secured and not running in debuggable privilege levels | R/W | 0

And the reason to put the cmderr 6 here is to tell the debugger the hart is not debugbale and do not waste time on it and expecting halted status. It could be optional in this case, but I remember it seems Paul suggested that no bad to reserve an error code, because just 2 lefted. 

>I propose to remove this statement or add it as optional. As far as I aware most of the implementations does not support denial for hart requests since they implement halt request as a debug interrupt. Moreover, if it remains as pending, it can be debugged after software change mdbgsec value later on.

For interrupt implementation, they could as well have denial. For example, they have to support the cmderr like 1 (busy), 2 (not supported), 4(not in required state). Thus, I don't think denial is a problem.

**Comment by IMG-S-Hopton** [comment]
> For interrupt implementation, they could as well have denial. For example, they have to support the cmderr like 1 (busy), 2 (not supported), 4(not in required state). Thus, I don't think denial is a problem

I believe this is (usually) done by the debug module not the core, so the core would not have a denial state.

**Comment by AoteJin** [comment]
The cmderr 3 indicates an exception occurred while executing the command. So, there must be a way for interrupt implemenation to tell the DM there is a error to be set. 

I quoted from debug spec:
_"The code there causes the hart to write to the Debug Module indicating an exception. Then the hart jumps back to the park loop. The DM infers from the write that there was an exception, and sets cmderr appropriately."_

In my point of view, the denial could be achieved by same mechanism.

**Comment by gokhankaplayan** [comment]
I am not sure denial can be achieved by the same mechanism because this approach requires some code running in debug mode. It implied that normal program execution is interrupted for the debug denial. My concern is about the security leak, that is external debugger will steal some time from normal program for denial case. Is it OK for security?

**Comment by joxie** [comment]
> The cmderr 3 indicates an exception occurred while executing the command. So, there must be a way for interrupt implemenation to tell the DM there is a error to be set.
> 
> I quoted from debug spec: _"The code there causes the hart to write to the Debug Module indicating an exception. Then the hart jumps back to the park loop. The DM infers from the write that there was an exception, and sets cmderr appropriately."_
> 
> In my point of view, the denial could be achieved by same mechanism.

 It is not a problem for execution based model but probably not that easy for abstract command based model

**Comment by gokhankaplayan** [comment]
> > The cmderr 3 indicates an exception occurred while executing the command. So, there must be a way for interrupt implemenation to tell the DM there is a error to be set.
> > I quoted from debug spec: _"The code there causes the hart to write to the Debug Module indicating an exception. Then the hart jumps back to the park loop. The DM infers from the write that there was an exception, and sets cmderr appropriately."_
> > In my point of view, the denial could be achieved by same mechanism.
> 
> It is not a problem for execution based model but probably not that easy for abstract command based model

It is a problem for execution based model since they execute special code in debug mode for exceptions. This method can be applied to security fault errors. But, it is not appropriate for denials.

**Comment by AoteJin** [comment]
For simplicity, the denial is removed and the halt request will be pending if debug is not allowed
